/**
 * Eden Codegen Output Tests
 *
 * Run the eden-generate script against sample controllers
 * and verify the output is valid TypeScript.
 */
import { describe, test, expect } from 'bun:test';
import { $ } from 'bun';
import fs from 'fs';

const OUTPUT = '/tmp/test-eden-output.ts';
const SCRIPT = 'scripts/eden-generate.ts';

describe('Eden Codegen > Output Validation', () => {
  test('should generate file with correct structure', async () => {
    await $`bun run ${SCRIPT} samples/eden-treaty/src/app.module.ts --output ${OUTPUT}`.quiet();

    const content = fs.readFileSync(OUTPUT, 'utf-8');

    // Header
    expect(content).toContain('AUTO-GENERATED by Eden Type Generator v3');
    expect(content).toContain("import { Elysia, t } from 'elysia'");

    // Interface
    expect(content).toContain('interface TodosItem');
    expect(content).toContain('id: number');
    expect(content).toContain('title: string');
    expect(content).toContain('done: boolean');

    // Route definitions
    expect(content).toContain('.get("/todos"');
    expect(content).toContain('.post("/todos"');
    expect(content).toContain('TodosItem[]');

    // Body schema
    expect(content).toContain('t.Object(');
    expect(content).toContain('title: t.String()');

    // Export
    expect(content).toContain('export type App = typeof _app');
  });

  test('should generate path params for basic-crud', async () => {
    await $`bun run ${SCRIPT} samples/basic-crud/src/app.module.ts --output ${OUTPUT}`.quiet();

    const content = fs.readFileSync(OUTPUT, 'utf-8');

    // Path params
    expect(content).toContain('/users/:id');
    expect(content).toContain('params: t.Object({ id: t.String() })');

    // Optional body field
    expect(content).toContain('t.Optional(t.String())');

    // Named interface dedup
    const matches = content.match(/interface UsersItem/g);
    expect(matches).toHaveLength(1); // deduplicated
  });

  test('should not contain invalid TypeScript syntax', async () => {
    await $`bun run ${SCRIPT} samples/eden-treaty/src/app.module.ts --output ${OUTPUT}`.quiet();

    const content = fs.readFileSync(OUTPUT, 'utf-8');

    // No interface Foo {}[] (invalid)
    expect(content).not.toMatch(/interface\s+\w+\s*\{[^}]*\}\[\]/);

    // No `any` in return types (we should have real types)
    expect(content).not.toContain('');
  });
});
