/**
 * AUTO-GENERATED by Eden Type Generator v3
 * Do NOT edit manually — regenerate with:
 *   bun run eden:generate samples/eden-treaty/src/app.module.ts --output samples/eden-treaty/eden.ts
 */
import { Elysia, t } from 'elysia';

// ─── Inferred Types ──────────────────────────────────────────────
interface TodosItem {
  id: number;
  title: string;
  done: boolean;
}

// ─── Route Definitions ──────────────────────────────────────────

const _app = new Elysia()
  .get("/todos", () => ({} as TodosItem[]))
  .post("/todos", () => ({} as TodosItem), { body: t.Object({ title: t.String() }) });

export type App = typeof _app;
