/**
 * AUTO-GENERATED by Eden Type Generator
 * Do NOT edit this file manually.
 * 
 * Regenerate with:
 *   bun run scripts/eden-generate.ts samples/eden-treaty/src/app.module.ts --output samples/eden-treaty/eden.d.ts
 * 
 * Usage with Eden Treaty:
 *   import { treaty } from '@elysiajs/eden';
 *   import type { App } from 'samples/eden-treaty/eden';
 *   const api = treaty<App>('http://localhost:3000');
 */
import { Elysia, t } from 'elysia';

const _app = new Elysia()
  .get("/todos", () => ({} as any), {})
  .post("/todos", () => ({} as any), { body: t.Object({}) });

export type App = typeof _app;
